//Fetch
export const LOAD_PERSONS = 'LOAD_PERSONS';
export const LOAD_PERSONS_SUCCESS = 'LOAD_PERSONS_SUCCESS';
export const LOAD_PERSONS_FAILURE = 'LOAD_PERSONS_FAILURE';

//LOGIN
export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT'

//Person list
export const FILTER_PERSON = 'FILTER_PERSON';
export const SORT_PERSON = 'SORT_PERSON';

//Add Person
export const ADD_PERSON = 'ADD_PERSON';
export const ADD_PERSON_FAILURE = 'ADD_PERSON_FAILURE';
export const ADD_PERSON_SUCCESS = 'ADD_PERSON_SUCCESS';

// fetch societe for add person form

export const FETCH_SOCIETE = 'FETCH_SOCIETE';
export const FETCH_SOCIETE_FAILURE = 'FETCH_SOCIETE_FAILURE';
export const FETCH_SOCIETE_SUCCESS = 'FETCH_SOCIETE_SUCCESS';

//Fetch
export const LOAD_PERSON_DATA = 'LOAD_PERSON_DATA';
export const LOAD_PERSON_DATA_SUCCESS = 'LOAD_PERSON_DATA_SUCCESS';
export const LOAD_PERSON_DATA_FAILURE = 'LOAD_PERSON_DATA_FAILURE';