//Fetch
export const LOAD_PERSON = 'LOAD_PERSON';
export const LOAD_PERSON_SUCCESS = 'LOAD_PERSON_SUCCESS';
export const LOAD_PERSON_FAILURE = 'LOAD_PERSON_FAILURE';

//LOGIN
export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';


export const FILTER_PERSON = 'FILTER_PERSON';
export const SORT_PERSON = 'SORT_PERSON';
